services:

  mongodb:
    image: mongo:7.0
    container_name: edgerunners-mongodb
    ports:
      - "27017:27017"

    volumes:
      - mongodb_data:/data/db  

  redis:
    image: redis:7-alpine
    container_name: edgerunners-redis
    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

  elasticsearch:
    image: elasticsearch:8.17.0
    container_name: edgerunners-elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  

    volumes:
      - es_data:/usr/share/elasticsearch/data

  server:
    build: ./server
    container_name: edgerunners-server
    ports:
      - "4000:4000"

    environment:
      - MONGODB_URL=mongodb://mongodb:27017/edgerunners
      - REDIS_URL=redis://redis:6379
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - mongodb
      - redis
      - elasticsearch

  client:
    build: ./client
    container_name: edgerunners-client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - server        

volumes:
  mongodb_data:
  redis_data:
  es_data:                      